### PR TITLE
[Feature]: Added Two-Fer Exercise

### PR DESCRIPTION
**Pull request by KTSnowy**
This PR adds the Two-Fer exercise

### CODE REVIEW

**Comment by KTSnowy** [comment]
Screen Shot 2022-07-25 at 22 28 22

**Comment by KTSnowy** [comment]
@0xE282B0 The version of gnuCOBOL that we're using on the Linux CI doesn't have the CONCAT Function?

**Comment by axtens** [comment]
Try [CONCATENATE](https://gnucobol.sourceforge.io/faq/index.html#function-concatenate)

**Comment by axtens** [comment]
Like i just said in slack, use STRING

**Comment by KTSnowy** [comment]
@axtens changed it to STRING

**Pull request merged**
