### PR TITLE
punctuation, indentation and a missing fullstop?

### PR DESCRIPTION
**Pull request by axtens**
As far as I can tell, there's nothing wrong with the code. However, I've changed the indent slightly and added an explicit END-IF.

### CODE REVIEW

**Comment by axtens** [comment]
The problem appears to with cobolcheck. Running cobolcheck locally passes perfectly. However the CI fails. The CI also shows tests comparing floating point numbers. But there are no floating point numbers in the tests nor in the proof.ci.cob code. 

@ErikSchierboom @KTSnowy 
What version of cobolcheck is being used?
```
C:\Users\bugma\Dropbox\Projects\exercism-tracks\loboc\exercises\practice\armstrong-numbers>pwsh test.ps1
Run cobolcheck.
CobolCheck: INFO 2023-06-25T13:52:41.558543300Z INF001: Attempting to load config from config.properties.
CobolCheck: INFO 2023-06-25T13:52:41.559546200Z INF002: Loaded config successfully from config.properties.
CobolCheck: INFO 2023-06-25T13:52:41.559546200Z INF003: Cobol-Check starting
CobolCheck: INFO 2023-06-25T13:52:41.560838900Z INF005: Log level is INFO.
CobolCheck: INFO 2023-06-25T13:52:41.561858Z INF006: Configuration settings: production.
CobolCheck: INFO 2023-06-25T13:52:41.563867900Z INF014: Error log for the test suite parser is set to: C:\Users\bugma\Dropbox\Projects\exercism-tracks\loboc\exercises\practice\armstrong-numbers\ParserErrorLog.txt.
CobolCheck: INFO 2023-06-25T13:52:41.565856400Z INF013: Output for generated COBOL test program is set to: C:\Users\bugma\Dropbox\Projects\exercism-tracks\loboc\exercises\practice\armstrong-numbers\test.cob.
CobolCheck: INFO 2023-06-25T13:52:41.578207800Z INF012: Successfully generated COBOL test program for src\armstrong-numbers.
CobolCheck: INFO 2023-06-25T13:52:41.578207800Z INF004: Cobol-Check terminating: 0
TESTSUITE:
Tests for Armstrong Numbers
00000000
0
     PASS:   1. Zero is an Armstrong number
00000005
5
     PASS:   2. Single-digit numbers are Armstrong numbers
00000001
10
     PASS:   3. There are no two-digit Armstrong numbers
00000153
153
     PASS:   4. Three-digit number that is an Armstrong number
00000001
100
     PASS:   5. Three-digit number that is not an Armstrong number
00009474
9474
     PASS:   6. Four-digit number that is an Armstrong number
00009843
9475
     PASS:   7. Four-digit number that is not an Armstrong number
09926315
9926315
     PASS:   8. Seven-digit number that is an Armstrong number
09864574
9926314
     PASS:   9. Seven-digit number that is not an Armstrong number

  9 TEST CASES WERE EXECUTED
  9 PASSED
  0 FAILED
=================================================
```

**Comment by glennj** [comment]
@axtens the Windows CI is using Cobol v3.2-dev, and the latest cobolcheck is fetched

See
- https://github.com/exercism/cobol/blob/main/.github/workflows/test-windows.yml
- https://github.com/exercism/cobol/blob/main/exercises/practice/armstrong-numbers/bin/fetch-cobolcheck.ps1

**Comment by ErikSchierboom** [comment]
Could the issue be that Windows use Cobol 3.2 and Linux uses 3.1.2?

**Comment by haodeon** [comment]
For some reason it seems to only fail when run from this repo.

I forked the repo and I manually ran the COBOL / Test (Windows) workflow on main branch.

https://github.com/haodeon/cobol/actions/runs/5713473555

It ran successfully and all tests passed.

Looking at previous runs for this workflow, it has been failing for some time and as recently as two weeks ago. However, I couldn't reproduce the failing test by forking repo and running the workflow.

**Comment by haodeon** [comment]
I threw a random commit into main branch of my fork to test CI and it was fine too.

https://github.com/haodeon/cobol/actions/runs/5714052820/job/15480603671

**Comment by ErikSchierboom** [comment]
Weird.

**Comment by haodeon** [comment]
The merge of this PR has triggered CI and the [workflow ](https://github.com/exercism/cobol/actions/runs/5714195462)has ran successfully.

@ErikSchierboom Can allergies and high-score be merged?

**Comment by ErikSchierboom** [comment]
@haodeon One merged. I'll do the other one once the merge conflict is fixed.

**Pull request merged**
