### PR TITLE
anagram-exercise-fix: Added contents to the fetch-cobolcheck{,.ps1} files.

### PR DESCRIPTION
**Pull request by SimaDovakin**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SimaDovakin I've just created and merged https://github.com/exercism/cobol/pull/157, which adds a `bin/sync-fetch-cobolcheck-files` that copies the `bin/fetch-cobolcheck` and `bin/fetch-cobolcheck.ps1` files to all exercises. Could you:

1. Rebase this PR
2. Check if the `bin/fetch-cobolcheck` and `bin/fetch-cobolcheck.ps1` are the most up-to-date versions
3. Run `bin/sync-fetch-cobolcheck-script` and update this PR

That way we are certain that all exercises have the same, correct version.

**Comment by SimaDovakin** [comment]
Thank you. I'll do it

**Comment by SimaDovakin** [comment]
I guess, I did rebase, but there is some issue with PowerShell test version. It can't run tests properly (as CI says problem with binary search exercise). I have no idea why. Maybe, I did something wrong.

**Comment by ErikSchierboom** [comment]
It looks like it could not download the file:

```
Invoke-Expression: D:\a\cobol\cobol\exercises\practice\binary-search\test.ps1:11
Line |
  11 |  Invoke-Expression "bin\cobolcheck.exe -p $slug"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The module 'bin' could not be loaded. For more information, run 'Import-Module bin'.
 ```
 
 Could be a GitHub rate limit.

**Comment by ErikSchierboom** [comment]
Seems weird that I can find cobolcheck for the other exercises, but not binary-search.

**Comment by ErikSchierboom** [comment]
@kapitaali Any idea?

**Comment by kapitaali** [comment]
In my experience the cobolcheck files work as intended and there's no need to touch them. It is the COBOL source code that needs to be edited instead. I have had many occasions where Win cobolcheck fails, but then after editing the COBOL source it works.

**Comment by SimaDovakin** [comment]
When I try to fetch cobolcheck.exe locally (I use PowerShell on Linux) it is fetched to `$HOME/cobolcheck/cobolcheck.exe`. Is it intended behavior?

**Comment by kapitaali** [comment]
I would venture to guess it is not. But can you run the checking in a linux terminal?

**Comment by ErikSchierboom** [comment]
> When I try to fetch cobolcheck.exe locally (I use PowerShell on Linux) it is fetched to $HOME/cobolcheck/cobolcheck.exe. Is it intended behavior?

I think it is though.

**Comment by ErikSchierboom** [comment]
I would probably merge this PR and fix CI in a separate PR.

**Comment by SimaDovakin** [comment]
> I would venture to guess it is not. But can you run the checking in a linux terminal?

In a Linux terminal I got some errors which connected to different path separators in Linux and Windows, but magically I can see test results)

**Comment by ErikSchierboom** [comment]
Let's merge this PR and then someone can fix the CI error in a follow-up PR.

**Comment by kapitaali** [comment]
I'm not sure what's wrong but now when I do test.sh on linux it does not fetch it (this used to work out of the box):

```
./test.sh 
Cobolcheck not found, try to fetch it.
curl: (56) Failure writing output to destination, passed 824 returned 4294967295
./test.sh: line 16: ./bin/cobolcheck: No such file or directory
COMPILE AND RUN TEST
cobc: test.cob: No such file or directory
```

**Comment by SimaDovakin** [comment]
> I'm not sure what's wrong but now when I do test.sh on linux it does not fetch it (this used to work out of the box):
> 
> ```
> ./test.sh 
> Cobolcheck not found, try to fetch it.
> curl: (56) Failure writing output to destination, passed 824 returned 4294967295
> ./test.sh: line 16: ./bin/cobolcheck: No such file or directory
> COMPILE AND RUN TEST
> cobc: test.cob: No such file or directory
> ```

Hmm.. @kapitaali Did you run it from track's root? I'll try it tomorrow.

**Comment by kapitaali** [comment]
no that's the exercism/cobol/anagram directory, trying to test the exercise

**Comment by SimaDovakin** [comment]
When I ran `./test.sh` I got this:
```bash
 Cobolcheck not found, try to fetch it.                                                                                                                                                        
curl: (23) Failure writing output to destination                                                                                                                                              
./test.sh: line 16: ./bin/cobolcheck: No such file or directory
COMPILE AND RUN TEST
test.cob:167: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:214: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:313: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:413: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:435: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:457: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:481: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers] 
test.cob:505: warning: alphanumeric literal has zero length; a SPACE will be assumed [-Wothers]
TESTSUITE:
Tests for Anagram
     PASS:   1. test_no_matches                                                                 
**** FAIL:   2. test_detect_two_anagrams                                                        
    EXPECTED <lemons,melons>, WAS <>
     PASS:   3. test_does_not_detect_anagram_subsets                                            
**** FAIL:   4. test_detects_anagram                                                            
    EXPECTED <inlets>, WAS <>
**** FAIL:   5. test_three_anagrams                                                             
    EXPECTED <gallery,regally,largely>, WAS <>
**** FAIL:   6. test_detects_multiple_anagrams_with_different_case                              
    EXPECTED <Eons,ONES>, WAS <>
     PASS:   7. test_does_not_detect_non_anagrams_with_identical_checksum                       
**** FAIL:   8. test_detects_anagrams_case_insensitively                                        
    EXPECTED <Carthorse>, WAS <>
**** FAIL:   9. test_detects_anagram_using_case_insensitive_subject                             
    EXPECTED <carthorse>, WAS <>
**** FAIL:  10. test_detects_anagrams_using_case_insensitive_possible_matches                   
    EXPECTED <Carthorse>, WAS <>
     PASS:  11. test_does_not_detect_an_anagram_if_the_original_word_is_repeated                
     PASS:  12. test_anagrams_must_use_all_letters_exactly_once                                 
     PASS:  13. test_words_are_not_anagrams_of_themselves                                       
     PASS:  14. test_words_are_not_anagrams_of_themselves_even_if_letter_case_is_partially_diffe
     PASS:  15. test_words_are_not_anagrams_of_themselves_even_if_letter_case_is_completely_diff
**** FAIL:  16. test_words_other_than_themselves_can_be_anagrams                                
    EXPECTED <Silent>, WAS <>
 
 16 TEST CASES WERE EXECUTED
  8 PASSED
  8 FAILED
=================================================
```
Interesting. Some tests are not passed now.

**Comment by SimaDovakin** [comment]
I reset my solution to anagram on website and then tested my example solution. All tests are passed.

**Comment by kapitaali** [comment]
Ok but that's not the behavior it used to exhibit. It's supposed to download cobolcheck for each execise's ./bin directory.

**Comment by SimaDovakin** [comment]
@kapitaali I created PR where I reverted `fetch-cobolcheck` and `fetch-cobolcheck.ps1` scripts and ran `./bin/sync-fetch-cobolcheck-files` to sync all fetch-cobolcheck scripts within each exercise https://github.com/exercism/cobol/pull/158. Now when I run `sudo ./bin/test` (it works only with root permission) from the repo's root all tests pass. I tried `sudo pwsh ./bin/test.ps1` and it also works but with some errors. When I try to run `./test.sh` in the anagram exercise's folder not all tests pass but when I ran `sudo ./bin/test` from repo's root all tests pass. It is weird.

**Comment by kapitaali** [comment]
here's the old fetch-cobolcheck, you may have this put back:

```
#!/usr/bin/env bash

# This file is inspired by https://github.com/exercism/configlet/blob/main/scripts/fetch-configlet.
# It is only used in the cobol track, and a copy of it is placed in every exercise folder.
# If you change something, make sure to upgrade all scripts in all exercises!

set -eo pipefail

readonly LATEST='https://api.github.com/repos/0xE282B0/cobol-check/releases/latest'

case "$(uname)" in
  Darwin*)   os='mac'     ;;
  Linux*)    os='linux'   ;;
  Windows*)  os='windows' ;;
  MINGW*)    os='windows' ;;
  MSYS_NT-*) os='windows' ;;
  *)         os='linux'   ;;
esac

case "${os}" in
  windows*) ext='.exe' ;;
  *)        ext='' ;;
esac

arch="$(uname -m)"

curlopts=(
  --silent
  --show-error
  --fail
  --location
  --retry 3
)

if [[ -n "${GITHUB_TOKEN}" ]]; then
  curlopts+=(--header "authorization: Bearer ${GITHUB_TOKEN}")
fi

suffix="${os}-${arch}${ext}"

get_download_url() {
  curl "${curlopts[@]}" --header 'Accept: application/vnd.github.v3+json' "${LATEST}" |
    grep "\"browser_download_url\": \".*/download/.*/cobol-check.*${suffix}\"$" |
    cut -d'"' -f4
}

main() {
  if [[ -d ./bin ]]; then
    output_dir="./bin"
  elif [[ $PWD == */bin ]]; then
    output_dir="$PWD"
  else
    echo "Error: no ./bin directory found. This script should be ran from a repo root." >&2
    return 1
  fi

  output_path="${output_dir}/cobolcheck${ext}"
  download_url="$(get_download_url)"
  curl "${curlopts[@]}" --output "${output_path}" "${download_url}"
  chmod +x "${output_path}"
}

main
```

**Pull request merged**
