### PR TITLE
add exercise: allergies

### PR DESCRIPTION
**Pull request by glennj**
Responding to http://forum.exercism.org/t/select-featured-exercises-for-jurassic-july/6018/8

COBOL folks, please comment on idioms.

Includes a small improvement to the `bin/test` script to allow a single exercise to be verified.

### CODE REVIEW

**Comment by glennj** [comment]
I have no idea why the armstrong-number tests are failing on windows.

**Comment by glennj** [comment]
@exercism/cobol team: this PR introduces a new exercise, but it breaks the _next_ exercise only on windows. Is there any kind of persistence between testing two consecutive exercises? Can someone investigate please?

**Comment by axtens** [comment]
I expect it's because there is the need to INITIALIZE the result variable at the beginning of the solution. As I recall the test framework doesn't do that for you.

**Comment by glennj** [comment]
Hi Bruce. My main difficulty is that it's a file I did not touch in this PR. How did it pass CI before this commit?

**Comment by axtens** [comment]
git and I have a tenuous friendship. How do I download your PR so that I can access the code and tests?

**Comment by glennj** [comment]
> git and I have a tenuous friendship. How do I download your PR so that I can access the code and tests?

You would clone my repo https://github.com/glennj/exercism-cobol
and checkout the `allergies` branch.

**Comment by axtens** [comment]
How do I get the source from the PR though? That's just the template.

**Comment by glennj** [comment]
@exercism/cobol The windows tests for armstrong-numbers (**not** touched by this PR) continues to fail. If you want to participate in 12in23 next month, I strongly urge y'all to investigate.

**Comment by haodeon** [comment]
Can someone rerun the checks?

I forked this repo, pulled in Glenn's branch and then manually ran the COBOL / Test (Windows) workflow.

https://github.com/haodeon/cobol/actions/runs/5713644207/job/15479395675

They all passed and the whole workflow completed successfully.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@glennj Could you fix the merge conflict? I'll merge once fixed

**Comment by ErikSchierboom** [comment]
Thanks

**Comment by axtens** [comment]
@glennj GnuCOBOL does have bit operations. E.g. https://gnucobol.sourceforge.io/faq/gcfaq.html#index-212

**Pull request merged**
