### PR TITLE
Yacht too

### PR DESCRIPTION
**Pull request by axtens**

### CODE REVIEW

**Comment by KTSnowy** [comment]
> yacht: proof solution did not pass the tests

@axtens what happened?

**Comment by axtens** [comment]
What happened was me not thinking about how cobolcheck runs things. I had written yacht.cob to be loaded and executed for each play. Cobolcheck however, loads the program once and then executes the tests in that environment. So I have to explicitly move zeroes to variables I could otherwise allow the working-storage to initialize for me.

**Comment by KTSnowy** [comment]
So is everything working now? Would that be an issue for the students?

**Review by KTSnowy — APPROVED** [review]

**Comment by axtens** [comment]
Everything working. As for it being an issue for the students ... they'd realize eventually

**Comment by 0xE282B0** [comment]
@axtens, Can we do:
```
           BEFORE-EACH
               MOVE ZEROES TO WS-COUNTER.
               MOVE ZEROES TO WS-RESULT.
           END-BEFORE
```
or would it have side effects?

**Comment by KTSnowy** [comment]
Hey @0xE282B0, the `BEFORE-EACH` keyword doesn't seem to be part of the COBOL standard, maybe it would be better not to use it. Which compilers support the `BEFORE-EACH` keyword?

**Comment by 0xE282B0** [comment]
@KTSnowy it's not Cobol it's part of the test framework:
https://github.com/openmainframeproject/cobol-check/wiki/A-Brief-Example#a-brief-sample

**Comment by KTSnowy** [comment]
> @KTSnowy it's not Cobol it's part of the test framework:

Ohhh that makes sense, I'm sorry. 

So maybe we could do that so that the students don't have to move ZEROES themselves, and we would probably have to explain that the variables already have zeroes in them to avoid confusion. Maybe with a comment?

**Comment by KTSnowy** [comment]
Would that cause any issues for the students?

**Comment by axtens** [comment]
> @axtens, Can we do:
> ```
>            BEFORE-EACH
>                MOVE ZEROES TO WS-COUNTER.
>                MOVE ZEROES TO WS-RESULT.
>            END-BEFORE
> ```
> or would it have side effects?

I can't think what side effects there would be. Exercism encourages students to read the test cases. The above would simplify off at least reduce the code in the proof

**Pull request merged**
