### PR TITLE
1 new exercise: binary-search

### PR DESCRIPTION
**Pull request by kapitaali**
Hi,

please find my exercise to the COBOL track: binary-search

no GOBACKs were used, instead EXIT PROGRAM was used (hopefully cobolcheck does not warn)

### CODE REVIEW

**Comment by kapitaali** [comment]
It appears the .cut file was an old version, fixed on my branch.

**Comment by axtens** [comment]
Regarding 
```
01 Teibel. 
         02 Taulukko               PIC 999 OCCURS 1 TO 20
                                   DEPENDING ON IDX.        
```
I wonder how you'd go with an `INDEXED BY` and then you can `SET index-name TO value` and then `SET index-name UP BY 1` or `SET index-name DOWN BY 1`

**Comment by kapitaali** [comment]
I haven't had the need to do any INDEX operations like SEARCH. But subscripts could be changed to INDEXes if needed.

**Comment by axtens** [comment]
Suggestion only. As long as it works if the bottom line

**Review by axtens — APPROVED** [review]

**Pull request merged**
