### PR TITLE
[LAUNCH!]: Turn the "active" key to true

### PR DESCRIPTION
**Pull request by KTSnowy**
Are we ready to launch the track?

- [x] @KTSnowy
- [x] @axtens
- [x] @0xE282B0
- [x] @kotp

This PR enables the track to appear to the public!

### CODE REVIEW

**Comment by kotp** [comment]
I do not have enough access to edit the message, but check my box.

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
Not even in the approved reviewers list.

**Review by axtens — APPROVED** [review]

**Comment by kotp** [comment]
Screenshot from 2022-07-29 09-25-57

@ErikSchierboom Missing the COBOL language from the footer area

**Comment by ErikSchierboom** [comment]
@kotp [PR opened to fix this](https://github.com/exercism/website/pull/2832)

**Pull request merged**
