### PR TITLE
[Feature]: Added Raindrops exercise

### PR DESCRIPTION
**Pull request by KTSnowy**
This PR adds the [Raindrops](https://github.com/exercism/problem-specifications/tree/main/exercises/raindrops) exercise

### CODE REVIEW

**Comment by KTSnowy** [comment]
dog-doggo

**Comment by KTSnowy** [comment]
> Hi, `test.sh` and `fetch-cobolcheck` need to be executable:

Hey @0xE282B0 I'm so sorry about all this. I tried writing this exercise on Windows, and it seems that Windows just removed the executable bit from those files (Thank Microsoft).

I had to move to macOS to fix it.

**Comment by KTSnowy** [comment]
It as a bit weird at first, because I just copied the same ones from the other exercises. So it seems that if you copy those executable files on Windows it just removes the executable bit?

**Review by 0xE282B0 — APPROVED** [review]
"PlingPlangPlong", I love this task 😂
LGTM

**Comment by KTSnowy** [comment]
> "PlingPlangPlong", I love this task 😂 LGTM

Hahahah PlingPlangPlong 😆

I'll go ahead and merge this

**Pull request merged**
