### PR TITLE
1 new exercise: binary-search

### PR DESCRIPTION
**Pull request by kapitaali**
Doing separate pull requests for new exercises. The first one is binary-search.

### CODE REVIEW

**Comment by kapitaali** [comment]
Fixed config.json on my branch, I wonder if I can make this run again without starting all over?

**Comment by axtens** [comment]
Before we go any further i must ask to address the following issue: cobol arrays start with item #1, that is, cobol arrays are 1-based. Your .CUT file however shows that you are assuming that the first item is #0 the way it is for 0-based C-family programming languages. 

Please change code and CUT to reflect a 1-based array layout.

**Comment by kapitaali** [comment]
I don't see any reference to zero index. Can you point out the line number in the file?

**Comment by kapitaali** [comment]
I don't see any reference to zero index. Can you point out the line number in the file?

In this file, https://github.com/kapitaali/exercism-cobol-track/blob/binary-search/exercises/practice/binary-search/tst/binary-search/binary-search.cut

doing ctrl-f for (0) brings up zero results.

**Comment by axtens** [comment]
L17-23 defines a 7-element array. Then you search for 6 (value of WS-ITEM). WS-RESULT is defined as 3, but in a 1-based array system, WS-RESULT should be 4. The 7-element array should be indexed from 1 to 7 but a WS-RESULT of 3 would only be returned if the 7-element array was indexed 0 to 6.

**Comment by kapitaali** [comment]
Yes, those answers were directly from the .json file. If it is needed to have the results be in COBOL indexing, then I would need to change the code. Going to drop this for now if it's not acceptable.

**Comment by axtens** [comment]
Do not drop. Change the CUT file. I expect that the Euphoria version of
this exercise had to change the test because it also is 1-based .

**Comment by axtens** [comment]
The problem specifications are written in JavaScript Object Notation and JavaScript is a 0-based language. Tests need to be rewritten for 1-based languages.

**Pull request closed without merging**
